pipeline {
    agent any

    environment {
        IMAGE_NAME = 'ravi1150/emp-service'   // Your Docker Hub image name
        IMAGE_TAG = 'latest'                  // Tag name
        CONTAINER_NAME = 'emp-service'        // Docker container name
    }

    stages {

        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/ravikumar1150/mvc-crudOperation', branch: 'jet-emp'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Remove existing container if running
                    sh 'docker rm -f $CONTAINER_NAME || true'

                    // Run new container
                    sh 'docker run -d --name $CONTAINER_NAME -p 9090:9090 $IMAGE_NAME:$IMAGE_TAG'
                }
            }
        }
    }
}
